### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by caller** [xiaxiaocao/jvcdiff#9]
hi,
I am creating my diffs with the commandline tool xdelta3 (version 3.0.7):

on some class of files I ALWAYS got the following issue, on other class files it works perfect.
Here a sample set:
http://www.mavinci.de/download/tmp/xdiff-badSample.zip

a call lile:
VcdiffDecoder.decode(new File("old.tgz"), new File("delta.xdiff"), new File("applied.tgz"));

will result in this:
java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkBounds(Buffer.java:559)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:181)
	at net.dongliu.vcdiff.io.ByteArrayStream.write(ByteArrayStream.java:81)
	at net.dongliu.vcdiff.VcdiffDecoder.decodeWindow(VcdiffDecoder.java:307)
	at net.dongliu.vcdiff.VcdiffDecoder.decode(VcdiffDecoder.java:93)
	at net.dongliu.vcdiff.VcdiffDecoder.decode(VcdiffDecoder.java:82)
	at net.dongliu.vcdiff.VcdiffDecoder.decode(VcdiffDecoder.java:60)
	at eu.mavinci_tmp.experiments.XDiffTest.main(XDiffTest.java:93)

on the commandline it works:
xdelta3 -d -f -s old.tgz delta.xdiff applied.tgz 

Thanks for your help!

-Marco

**Comment by xiaxiaocao** [comment]
Xdelta3 support external compress, decompress gzip files before real decode job. Jvcdiff do not do this no.
As a work round, you can decompress old.tgz first(with java or gzip -d), and then call Vcdiff.decode()

**Comment by caller** [comment]
Would it be possible to integrate integrate it directly in jvcdiff?
Otherwise I would do a java wrapper for your code

Cheers
Marco

Sent from my android phone
Am 07.06.2015 06:45 schrieb "Liu Dong" <notifications@github.com>:

**Comment by xiaxiaocao** [comment]
It could be, however currently have not plan for this.

**Comment by caller** [comment]
hi,

it works now fine for me, but I have no clue how to integrate this in a generic way:


	public static void decompressGzipFile(File gzipFile, File newFile) throws IOException {
        try (FileInputStream fis = new FileInputStream(gzipFile);
        		GZIPInputStream gis = new GZIPInputStream(fis);
        		FileOutputStream fos = new FileOutputStream(newFile))
		{
            byte[] buffer = new byte[1024];
            int len;
            while((len = gis.read(buffer)) != -1){
                fos.write(buffer, 0, len);
            }
        	
        }
    }
 
    public static void compressGzipFile(File file, File gzipFile) throws IOException {
        try (FileInputStream fis = new FileInputStream(file);
        		FileOutputStream fos = new FileOutputStream(gzipFile);
        		GZIPOutputStream gzipOS = new GZIPOutputStream(fos))
		{
        	byte[] buffer = new byte[1024];
            int len;
            while((len=fis.read(buffer)) != -1){
                gzipOS.write(buffer, 0, len);
            }
        }
    }

cheers

-marco

**Comment by xiaxiaocao** [comment]
What does 'a generic way' mean?
The while code looks like:
decompressGzipFile(new File("old.tgz"), new File("old.tar");
VcdiffDecoder.decode(new File("old.tar"), new File("delta.xdiff"), new File("applied.tar"));
compressGzipFile(new File("applied.tar"), new File("applied.tgz"))

VcdiffDecoder now can not take a InputStream/OutputStream as parameter, the code is somehow inefficient.

**Comment by caller** [comment]
hi,

your right, thats the way my code currently works, but working on input
streams isn't more difficoult at all, the (de)compress methods are just
piping the data through special streams, so you could wrap your usual
stream also through this, if you know that we are working with a gzip
file... and I would prefer to do the wrapping inside your code, than it
could be much more efficient....
the decision if this is a gz file or not, should be done automatically by
file header (not by file extension!!!), if this isn't possible, a
additional parameter would also be fine.

cheers

-marco

2015-06-10 4:47 GMT+02:00 Liu Dong <notifications@github.com>:

> What does 'a generic way' mean?
> The while code looks like:
> decompressGzipFile(new File("old.tgz"), new File("old.tar");
> VcdiffDecoder.decode(new File("old.tar"), new File("delta.xdiff"), new
> File("applied.tar"));
> compressGzipFile(new File("applied.tar"), new File("applied.tgz"))
>
> VcdiffDecoder now can not take a InputStream/OutputStream as parameter,
> the code is somehow inefficient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xiaxiaocao/jvcdiff/issues/9#issuecomment-110566947>.
>



-- 
Dr. Marco Möller
Geschäftsführer / CEO
MAVinci GmbH
Unmanned Aircraft Systems

mobil: +49 (0)173 / 20 51 706
fax: +49 (0)6227-398 2757
marco.moeller@mavinci.de
http://www.mavinci.de

Opelstraße 8a
68789 St. Leon-Rot
Germany

USt-IdNr.: DE264462348
Amtsgericht - Mannheim
HRB 710216, Sitz St. Leon-Rot
CEO: Cornelius Claussen, Johanna Claussen, Marco Möller, Michael Niesen

**Comment by xiaxiaocao** [comment]
Technically, yes it is,  need some modification to input and output.

**Comment by caller** [comment]
ok, but even without all the piping stuff, it would be great if you dont
have to think about if files might be a tar, and you could just use your
API and it just works ;-)

efficiency isn't important in my application

2015-06-10 8:27 GMT+02:00 Liu Dong <notifications@github.com>:

> Technically, yes it is, need some modification to input and output.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xiaxiaocao/jvcdiff/issues/9#issuecomment-110612798>.
>



-- 
Dr. Marco Möller
Geschäftsführer / CEO
MAVinci GmbH
Unmanned Aircraft Systems

mobil: +49 (0)173 / 20 51 706
fax: +49 (0)6227-398 2757
marco.moeller@mavinci.de
http://www.mavinci.de

Opelstraße 8a
68789 St. Leon-Rot
Germany

USt-IdNr.: DE264462348
Amtsgericht - Mannheim
HRB 710216, Sitz St. Leon-Rot
CEO: Cornelius Claussen, Johanna Claussen, Marco Möller, Michael Niesen

**Comment by xiaxiaocao** [comment]
Yes. This could be a feature request.
